version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - '5001:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-docker-container:
    build: .
    environment:
      - PORT=5001
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
    