version: '3'
services:
  node-docker-container:
    build: .
    ports: 
      - '5001:5001'
    environment:
      - PORT=5001

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
    